#+TITLE:  By Jove! Yet Another JavaScript Editing Mode
#+AUTHOR: John Hooks
#+EMAIL: john@bitmachina.com
#+DATE: <2017-04-22 Sat>
#+STARTUP: indent
#+STARTUP: hidestars

** About
This project is an attempt to create a new JavaScript editing mode for
Emacs.

Jove includes a striped down port of the [[https://github.com/ternjs/acorn][Acorn]] parser in order to
provide complex highlighting and indentation functionality.

*** Inspiration
- [[https://github.com/marijnh/parse-js][parse-js]] written in Common Lisp by Marijn Haverbeke
- [[https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js][CodeMirror]]
- [[https://github.com/ternjs/acorn][Acorn]]
- [[https://github.com/mishoo/UglifyJS2][UglifyJS]]
- [[https://github.com/mooz/js2-mode][js2-mode]]
*** Reading on JavaScript Parsers
- [[http://codemirror.net/1/story.html][Implementing a Syntax-Highlighting JavaScript Editor—In JavaScript]] 
  By Marijn Haverbeke
- [[http://marijnhaverbeke.nl/blog/acorn.html][Acorn: yet another JavaScript parser]]
  By Marijn Haverbeke
- [[http://lisperator.net/pltut/][How to implement a programming language in JavaScript]]
  By Mihai Bazon

** Installation
Jove is still a work in progress. Though if you want to check it out,
clone this repository, add it to your ~load-path~ and then require it.
Optionally if you think its pretty cool, add it as the default mode for
JavaScript.

#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name "elisps/jove"
                                            user-emacs-directory))
  (require 'jove)
  (add-to-list 'auto-mode-alist '("\\.js$" . jove-mode))
#+end_src

** Reasoning
Shear madness.

After getting frustrated in an attempt to modify the indentation code
of ~js.el~, I concluded a /simple*/ syntax parser would provide a more
complete understanding of the code for editing purposes. Plus I needed
something to do in my spare time.

\star ha, ha, ha...

** Working
The functions of the lexer are complete and tested. The parser
functions are mostly complete and untested. I have been performing
informal tests of the parser with [[http://underscorejs.org/][Underscore]] and [[http://jquery.com][JQuery]], it seems to
be parsing everything correctly.

** Goals
- JSX indentation is currently non-functional. The biggest hurdle is
  combining the legacy indentation code from [[https://github.com/johnhooks/js-align][js-align]] and newer AST
  funcationality. The end goal is to base all indentation off the AST,
  meanwhile I want a solution that can use either method.

- Auto-pairing of JSX tags.

- Highlighting of JSX tag pairs.

