#+TITLE:  By Jove! Yet Another JavaScript Editing Mode
#+AUTHOR: John Hooks
#+EMAIL: john@bitmachina.com
#+DATE: <2017-04-21 Fri>
#+STARTUP: indent
#+STARTUP: hidestars

** About
This project is an attempt to create a new JavaScript editing mode for
Emacs.

Jove includes a striped down port of the [[https://github.com/ternjs/acorn][Acorn]] parser in order to
provide complex highlighting and indentation functionality.

*** Inspiration
- [[https://github.com/marijnh/parse-js][parse-js]] written in Common Lisp by Marijn Haverbeke
- [[https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js][CodeMirror]]
- [[https://github.com/ternjs/acorn][Acorn]]
- [[https://github.com/mishoo/UglifyJS2][UglifyJS]]
- [[https://github.com/mooz/js2-mode][js2-mode]]
*** Reading on JavaScript Parsers
- [[http://codemirror.net/1/story.html][Implementing a Syntax-Highlighting JavaScript Editor—In JavaScript]] 
  By Marijn Haverbeke
- [[http://marijnhaverbeke.nl/blog/acorn.html][Acorn: yet another JavaScript parser]]
  By Marijn Haverbeke
- [[http://lisperator.net/pltut/][How to implement a programming language in JavaScript]]
  By Mihai Bazon

** Installation
Probably shouldn't not do that quite yet... getting close though!

** Reasoning
Shear madness.

After getting frustrated in an attempt to modify the indentation code
of ~js.el~, I concluded a /*simple*/ (ha, ha, ha...)  syntax parser
would provide a more complete understanding of the code for editing
purposes. Plus I needed something to do in my spare time.

** Working
The functions of the lexer are complete and tested. The parser
functions are mostly complete and untested. I have been performing
informal tests of the parser with [[http://underscorejs.org/][Underscore]] and [[http://jquery.com][JQuery]], it seems to
be parsing everything correctly.
